### ISSUE TITLE
Idea: dark theme?

### ISSUE THREAD

**Issue by jhogervorst** [davidbwaters/macos-modern-vscode-theme#1]
The theme looks very nice, great work! 😄

Any plans for a dark version? With dark mode in MacOS Mojave, it would be cool to have a light and dark macOS theme for VS Code (and switch between them using an extension like [NightSwitch-Lite](https://marketplace.visualstudio.com/items?itemName=gharveymn.nightswitch-lite)).

**Comment by philsinatra** [comment]
[https://marketplace.visualstudio.com/items?itemName=philsinatra.macos-dark-mode-theme](https://marketplace.visualstudio.com/items?itemName=philsinatra.macos-dark-mode-theme)

**Comment by jhogervorst** [comment]
@philsinatra Thanks, I’ll give it a try!

**Comment by davidbwaters** [comment]
Hey, sorry for not replying sooner. I finally got around to doing this.  I still need to tweak the scheme and UI colors a bit.  I’ll keep updating it when I have the time.  Hope you enjoy it!
