### ISSUE TITLE
How to get the line spacing and collapse arrows from the light version screenshot?

### ISSUE THREAD

**Issue by TheTourer** [davidbwaters/macos-modern-vscode-theme#10]
Firstly, thanks so much for this theme. Makes an otherwise hard-on-the-eyes, non-native application match the UI of macOS as it should by default.

I am using the Dark Version of this theme and wondering how to make the Explorer line height/spacing and collapse/expand arrows match those depicted in the Light Version screenshot in the main README (show below). I've been searching far and wide for a solution to this, but have come up short thus far.

Thanks in advance for your help, and thanks again for this great theme!
![](https://github.com/davidbwaters/macos-modern-vscode-theme/raw/master/images/screenshot1.png)

**Comment by davidbwaters** [comment]
Try adjusting VSCode's zoom setting:

`"window.zoomLevel": -0.5,`

If that's too general, you can always use a plugin like [Cusomize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) and go to `Help > Toggle Developer Tools` in VSCode to inspect and override the padding values with some custom CSS overrides.
