### ISSUE TITLE
Template literals are not highlighted when using the Catalina color scheme

### ISSUE THREAD

**Issue by jonpalmisc** [davidbwaters/macos-modern-vscode-theme#11]
JavaScript (and probably TypeScript too) template literals are not highlighted properly when using the Catalina Dark color scheme. See line 41 in the screenshot below.

![image](https://user-images.githubusercontent.com/41548458/85134046-de2a8600-b209-11ea-9182-8cc2d69ab0f0.png)

**Comment by jonpalmisc** [comment]
I was able to fix this by adding the following to my `settings.json`:
```json
"editor.tokenColorCustomizations": {
    "strings": "#FE8170"
}
```

**Comment by jonpalmisc** [comment]
Created a PR (#12).

**Comment by davidbwaters** [comment]
Merged.  Thanks.
