### ISSUE TITLE
Support markdown syntax

### ISSUE THREAD

**Issue by phlippieb** [davidbwaters/macos-modern-vscode-theme#13]
For some reason, Markdown syntax highlighting doesn't work when I have this theme on. It does work with other themes.

Here's some markdown with a MacOS Modern dark theme:

<img width="712" alt="Screenshot 2020-08-23 at 12 14 58" src="https://user-images.githubusercontent.com/2232699/90976068-524f1600-e53a-11ea-907b-908964a83c10.png">

Here's the same screen with the Dracula theme, to show that it works with other themes:

<img width="712" alt="Screenshot 2020-08-23 at 12 15 09" src="https://user-images.githubusercontent.com/2232699/90976079-66931300-e53a-11ea-81d6-cc8ef508bbc7.png">

(I don't fully understand VSCode themes, so I apologise if this isn't the right place for issue)

**Comment by davidbwaters** [comment]
Fixing
