### ISSUE TITLE
Modern Dark Big Sur - Text on Welcome page is barely readable

### ISSUE THREAD

**Issue by vinhphm** [davidbwaters/macos-modern-vscode-theme#14]
![image](https://user-images.githubusercontent.com/75784849/115837302-9fc1b100-a442-11eb-8e98-6d67532e7606.png)

If it were a little bit lighter, that would be great.

**Comment by davidbwaters** [comment]
Ooh, yeah that's no good.  I'll take a look.

**Comment by davidbwaters** [comment]
should be fixed :)
