### ISSUE TITLE
this isn't issue but i wanted to say you something

### ISSUE THREAD

**Issue by Hetp05** [davidbwaters/macos-modern-vscode-theme#15]
Hello there, this isn't issue but I am telling you that I have you little bit of your code in [my theme extension](https://github.com/Hetp05/xcode-theme-for-vscode) and don't worry I have give your name in my [credit.md](https://github.com/Hetp05/xcode-theme-for-vscode/blob/main/credits.md#user-content-color-file-icon-theme).

If you want I can remove all code which i coped from you.

**Comment by davidbwaters** [comment]
No problem.  Nice work! Thanks for crediting me!
