### ISSUE TITLE
File Icons not showing

### ISSUE THREAD

**Issue by Qpernicus** [davidbwaters/macos-modern-vscode-theme#16]
No this is not a ' i Use Arch Btw' , but i use arch with Qtile, and when i select your 'Legit finder icons' , it shows nothing. 

Am i  missing some sort of dependency/icon-set or something?

i get only blank paper icons.

**Comment by davidbwaters** [comment]
Can you screenshot?  The icons for files are just a generic document, they aren't customized per type, similar to how macOS treats them.

**Comment by nickkaczmarek** [comment]
Same issue here. File names hidden but you can see the swift file.

Using these settings:


```
"workbench.productIconTheme": "macos-modern",

// macOS Modern Tweaks
"editor.fontSize": 14,
"editor.fontFamily": "SF Mono, Monaco",
"editor.fontWeight": "normal",
"window.titleBarStyle": "native",
"window.nativeTabs": true,
"window.zoomLevel": 1,
"workbench.iconTheme": "macos-modern-legit-xcode-icon-theme",
 
 // Disable Tab File Icons
 "workbench.editor.showIcons": false,
 // Disable Red Sidebar Errors
 "problems.decorations.enabled": false,

  // Activitus Bar
"activitusbar.activeColour": "#615F61",
"workbench.activityBar.visible": true,

// Project Manager
"projectManager.treeview.visible": false,
```

<img width="413" alt="Screen Shot 2022-11-01 at 12 49 52" src="https://user-images.githubusercontent.com/9044401/199303330-8e2ebce2-cd41-42ec-b347-5e5b944ffdb1.png">

**Comment by davidbwaters** [comment]
Yeah, that's how they are supposed to look.  They aren't customized per file-type.  Sorry for the confusion.  I might add a more custom version in the future.

**Comment by nickkaczmarek** [comment]
Ah right on. That makes sense. Thanks for making such a cool extension. I see now that the original author of this issue isn't using macOS and I am so I wonder if my response has nothing to do with theirs.

**Comment by davidbwaters** [comment]
No problem.  I'm gonna go ahead and close this then.
