### ISSUE TITLE
Is the "Title Bar Search Box" part of this extension?

### ISSUE THREAD

**Issue by lzlrd** [davidbwaters/macos-modern-vscode-theme#17]
In the README images, the title bar seems to have a search box and be a few pixels wider than VS Code's default:

<img width="714" alt="Screenshot 2022-10-20 at 15 28 54" src="https://user-images.githubusercontent.com/24303423/196978798-bd8295a5-dd2d-475d-92ba-cf12e0cce1f8.png">

However, even though I'm using the `native` style title bar (as well as the other recommended settings) it looks like this to me:

<img width="1285" alt="Screenshot 2022-10-20 at 15 37 20" src="https://user-images.githubusercontent.com/24303423/196979270-a52a3d0d-adc0-41ee-92b3-3dc3389776ae.png">

Is that provided by another extension or have I misconfigured the layout?

**Comment by davidbwaters** [comment]
VSCode has improved its title bar custom mode to be much closer to native, so I'm using that now.  Feel free to change it to suit your needs.
