### ISSUE TITLE
how to find the lost classic themes

### ISSUE THREAD

**Issue by m666m** [davidbwaters/macos-modern-vscode-theme#18]
Thank you for making such a useful theme! This is my favorite theme color.

I found that with the update, the previous classic themes have disappeared.

I like `Catalina` color configuration very much.

How to find other classic themes, such as `Catalina`. 

Thanks a lot!

**Comment by davidbwaters** [comment]
Thanks!  I just renamed them to Ventura, so they should still be there!

**Comment by m666m** [comment]
Oh, I see. Thank you！
