### ISSUE TITLE
Error colors in file explorer are too dark

### ISSUE THREAD

**Issue by peyao** [davidbwaters/macos-modern-vscode-theme#4]
<img width="1705" alt="Screen Shot 2019-07-02 at 5 13 31 PM" src="https://user-images.githubusercontent.com/2942493/60554549-e170ed00-9cec-11e9-9dd8-bf8923a625f6.png">

Not sure if it's another extension causing this issue.

I'm seeing files that have errors in them have their text too dark in the file explorer view.  Normally, I would expect them to be orange/red.

Example of another dark theme (Dracula) with the correct file explorer color:
<img width="1705" alt="Screen Shot 2019-07-02 at 5 19 41 PM" src="https://user-images.githubusercontent.com/2942493/60554731-ae7b2900-9ced-11e9-9148-3fb7d9436132.png">

**Comment by davidbwaters** [comment]
This should be fixed.  I didn’t notice the issue because I had problems decorations disabled in settings (`problems.decorations.enabled": false`) because I found the sidebar colors annoying.  Just pushed the change so it should update in a minute.
