### ISSUE TITLE
Native appearance for scrollbars

### ISSUE THREAD

**Issue by ascarter** [davidbwaters/macos-modern-vscode-theme#5]
The scrollbars don't look quite right. The shape of the indicator should be rounded

This is from safari - notice the shape of the indicator:

<img width="1198" alt="Screen Shot 2019-08-16 at 4 37 28 PM" src="https://user-images.githubusercontent.com/4931/63203417-24401780-c044-11e9-930a-d21e9bb1e8a3.png">

In VSCode, the shape and the size seem wrong:

<img width="1136" alt="Screen Shot 2019-08-16 at 4 38 50 PM" src="https://user-images.githubusercontent.com/4931/63203442-55204c80-c044-11e9-9961-107bbdd19161.png">

**Comment by davidbwaters** [comment]
Good call.  I'll see what I can do to make them look more native.

**Comment by davidbwaters** [comment]
As far as I know, the only way to edit this would be to add a CSS stylesheet which can be done only with hackish solutions.  I plan to make one at some point for stuff like this, but I have know idea when.  If anyone wants to use the inspector and write some styles I will add it, but I'm closing this for now.  If anyone wants to contribute a solution for this, LMK.
