### ISSUE TITLE
Move close indicator on tabs to left

### ISSUE THREAD

**Issue by ascarter** [davidbwaters/macos-modern-vscode-theme#6]
The `x` to close a tab should appear on the left not the right. Ideally it should also only show when hover too.

Example in Safari:

<img width="1539" alt="Screen Shot 2019-08-16 at 4 40 59 PM" src="https://user-images.githubusercontent.com/4931/63203502-a16b8c80-c044-11e9-9515-de66b2ecb433.png">

**Comment by ascarter** [comment]
Found this setting which does move the button:

```"workbench.editor.tabCloseButton": "left",```

So I guess just adding a hide when not hovering on the button.

**Comment by davidbwaters** [comment]
I'll look into this when I get some time. Thanks for pointing.

**Comment by davidbwaters** [comment]
I will look into this and will add the setting to recommended settings, but this would have to be done with CSS and can't be added to the theme itself.  If anyone has a solution, PR's welcome or LMK.
