### ISSUE TITLE
 Find widget can't tell if the mouse hover and the icon are clicked 

### ISSUE THREAD

**Issue by m666m** [davidbwaters/macos-modern-vscode-theme#7]
From the Code release note v1.37：

Button toggle active state in Find widget
We've updated the Find widget's button toggle active state with a filled background so that you can now easily tell when you are focused on an active toggle. This appears in the Search view, Find and Replace, and Terminal Find.

With this update, we've introduced a new theme color, inputOption.activeBackground, to control the background color of the toggle active state. This color reuses focusBorder so that it works better with themes by default. We've also set the default for inputOption.activeBorder to transparent so that the border is only used for focus.

**Comment by davidbwaters** [comment]
I'll add something to address this when I can.

**Comment by m666m** [comment]
I found an alternative. In the setting.json, add the following 
"workbench.colorCustomizations": {
        "inputOption.activeBackground": "#929292",
    },

**Comment by davidbwaters** [comment]
Merging this in now.  Thanks.
