### ISSUE TITLE
Split group active tabs are too dim when group is not in focus

### ISSUE THREAD

**Issue by hugginsio** [davidbwaters/macos-modern-vscode-theme#9]
Whenever the editor is split in half, the text of the active tab has poor contrast with the tab background whenever that group is not in focus.

In this image, group 1 (left) is in focus. The text of the active tab of group 2, `.gitignore` here, is the text I'm referencing.

<img width="1196" alt="Screen Shot 2020-04-22 at 9 12 59 PM" src="https://user-images.githubusercontent.com/5430818/80051560-0d5c9980-84de-11ea-9965-75fd918be997.png">

Fantastic theme. Thanks for your hard work!

**Comment by davidbwaters** [comment]
Thanks.  I'll fix this when I get a chance.

**Comment by davidbwaters** [comment]
Sorry for delay.  Fixed.
